###
# Welcome to the new js2coffee 2.0, now
# rewritten to use the esprima parser.
# try it out!
###

$(document).ready ->

  ### activate sidebar ###

  $('#sidebar').affix offset: top: 235

  ### activate scrollspy menu ###

  $body = $(document.body)
  navHeight = $('.navbar').outerHeight(true) + 10
  $body.scrollspy
    target: '#leftCol'
    offset: navHeight

  ### smooth scrolling sections ###

  $('a[href*=#]:not([href=#])').click ->
    if location.pathname.replace(/^\//, '') == @pathname.replace(/^\//, '') and location.hostname == @hostname
      target = $(@hash)
      target = if target.length then target else $('[name=' + @hash.slice(1) + ']')
      if target.length
        $('html,body').animate { scrollTop: target.offset().top - 50 }, 1000
        return false
    return
  return

# ---
# generated by js2coffee 2.2.0